// GET http://localhost:3000/

POST http://localhost:3000/
Content-Type: application/json

{
  "message": "Which models are at least 65 units in height and 800 fire rating temp and is not waterproof?"
}